version: "3.4"

services:
  animatedgifme:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/animatedgifme
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/animatedgifme/node_modules
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  gem_cache:
  db_data:
  node_modules:
